from __future__ import annotations

from pathlib import Path

import final_hardening as hardening


_prior_preflight = hardening._strict_creative_preflight


def normalized_output_name(job) -> str:
    name = Path(job.filename).name
    target_suffix = ".png" if job.kind == "image" else ".mp4"
    path = Path(name)
    if path.suffix.lower() != target_suffix:
        path = path.with_suffix(target_suffix)
    return path.name.lower()


def strict_filename_preflight(output, unit: dict) -> list[str]:
    violations = list(_prior_preflight(output, unit))
    normalized = [normalized_output_name(job) for job in output.creative_jobs]
    if len(normalized) != len(set(normalized)):
        violations.append(
            "Creative jobs must resolve to distinct normalized output filenames."
        )

    for job in output.creative_jobs:
        suffix = Path(job.filename).suffix.lower()
        if job.kind == "image" and suffix != ".png":
            violations.append(
                f"Image asset {job.asset_id} must use a .png filename so "
                "generated bytes, MIME type, and Runway reference encoding agree."
            )
        if job.kind == "video" and suffix != ".mp4":
            violations.append(
                f"Video asset {job.asset_id} must use a .mp4 filename."
            )
    return violations


hardening._strict_creative_preflight = strict_filename_preflight
