#!/usr/bin/env node
/**
 * Generate (or verify) sitemap.xml from what is actually in the repository.
 *
 * Hand-edited sitemaps drift: pages ship, the file keeps yesterday's dates, and
 * <lastmod> quietly becomes a value Google has no reason to trust. Google only
 * uses <lastmod> while it stays consistently and verifiably accurate:
 * https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
 *
 * The page list is derived, not maintained by hand: any HTML file that declares
 * a canonical URL and is not marked noindex belongs in the sitemap. Adding a
 * page therefore adds it to the sitemap; forgetting to is caught by --check.
 *
 * <lastmod> is the date of the last commit that touched the page, so it moves
 * when the page's content moves and not when an unrelated file is edited.
 * Uncommitted local edits count as "today" so a freshly-edited page is never
 * published with a stale date.
 *
 *   node scripts/build-sitemap.mjs           # rewrite sitemap.xml
 *   node scripts/build-sitemap.mjs --check   # fail if sitemap.xml is stale
 */

import { execFileSync } from 'node:child_process';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(new URL('../', import.meta.url).pathname);
const ORIGIN = 'https://www.familyfindersbook.com';
const SITEMAP = resolve(root, 'sitemap.xml');

/** Crawl priority and change frequency by page role. Editorial, not derived. */
const WEIGHTS = [
  { match: /^index\.html$/, changefreq: 'monthly', priority: '1.0' },
  { match: /^order\.html$/, changefreq: 'monthly', priority: '0.9' },
  { match: /^how-it-works\.html$/, changefreq: 'monthly', priority: '0.8' },
  { match: /^family-emergency-planning\.html$/, changefreq: 'monthly', priority: '0.7' },
  { match: /^important-documents\.html$/, changefreq: 'monthly', priority: '0.7' },
  { match: /^in-case-of-death-binder\.html$/, changefreq: 'monthly', priority: '0.7' },
  { match: /^letter-of-instruction\.html$/, changefreq: 'monthly', priority: '0.7' },
  { match: /^about\.html$/, changefreq: 'yearly', priority: '0.6' },
  { match: /^contact\.html$/, changefreq: 'yearly', priority: '0.5' },
  { match: /^start\.html$/, changefreq: 'yearly', priority: '0.4' },
  { match: /.*/, changefreq: 'yearly', priority: '0.3' },
];

function weightFor(file) {
  return WEIGHTS.find((w) => w.match.test(file));
}

function git(args) {
  try {
    return execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
}

const today = new Date().toISOString().slice(0, 10);

function lastModified(file) {
  const dirty = git(['status', '--porcelain', '--', file]);
  if (dirty) return today;
  const committed = git(['log', '-1', '--format=%cs', '--', file]);
  // Empty means no history here (a shallow CI clone, or a brand-new file).
  return committed || today;
}

async function canonicalPages() {
  const entries = await readdir(root, { withFileTypes: true });
  const pages = [];
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.html')) continue;
    const html = await readFile(resolve(root, entry.name), 'utf8');
    const robots = html.match(/<meta\s+name="robots"\s+content="([^"]*)"/i)?.[1] ?? '';
    if (/noindex/i.test(robots)) continue;
    const canonical = html.match(/<link\s+rel="canonical"\s+href="([^"]+)"/i)?.[1];
    if (!canonical) continue;
    pages.push({ file: entry.name, loc: canonical, lastmod: lastModified(entry.name) });
  }
  // Home first, then the order of the editorial weights, then alphabetical.
  const rank = (file) => WEIGHTS.findIndex((w) => w.match.test(file));
  return pages.sort((a, b) => rank(a.file) - rank(b.file) || a.file.localeCompare(b.file));
}

function render(pages) {
  const body = pages
    .map(({ file, loc, lastmod }) => {
      const { changefreq, priority } = weightFor(file);
      return [
        '  <url>',
        `    <loc>${loc}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${changefreq}</changefreq>`,
        `    <priority>${priority}</priority>`,
        '  </url>',
      ].join('\n');
    })
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/build-sitemap.mjs. Run "npm run sitemap" after content changes. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

const pages = await canonicalPages();
if (!pages.length) {
  console.error('Sitemap build failed: no canonical, indexable pages found.');
  process.exit(1);
}

const expected = render(pages);
const check = process.argv.includes('--check');

if (!check) {
  await writeFile(SITEMAP, expected, 'utf8');
  console.log(`sitemap.xml written with ${pages.length} canonical pages`);
  process.exit(0);
}

const current = await readFile(SITEMAP, 'utf8').catch(() => '');
const problems = [];

for (const { loc } of pages) {
  if (!current.includes(`<loc>${loc}</loc>`)) problems.push(`missing canonical page: ${loc}`);
}
for (const loc of [...current.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1])) {
  if (!pages.some((p) => p.loc === loc)) problems.push(`sitemap lists a page that is no longer canonical/indexable: ${loc}`);
  if (!loc.startsWith(`${ORIGIN}/`)) problems.push(`sitemap lists a URL outside the canonical origin: ${loc}`);
}
for (const stamp of [...current.matchAll(/<lastmod>([^<]+)<\/lastmod>/g)].map((m) => m[1])) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(stamp)) problems.push(`invalid lastmod value: ${stamp}`);
  else if (stamp > today) problems.push(`lastmod is in the future: ${stamp}`);
}

// Staleness: only assert it where git history is actually available, so a
// shallow CI checkout reports nothing rather than reporting noise.
const currentStamps = new Map(
  [...current.matchAll(/<loc>([^<]+)<\/loc>\s*<lastmod>([^<]+)<\/lastmod>/g)].map((m) => [m[1], m[2]])
);
if (git(['rev-parse', '--is-shallow-repository']) === 'false') {
  for (const { file, loc, lastmod } of pages) {
    const recorded = currentStamps.get(loc);
    if (recorded && recorded < lastmod) {
      problems.push(`${file} changed on ${lastmod} but sitemap still says ${recorded} — run "npm run sitemap"`);
    }
  }
}

if (problems.length) {
  console.error('Sitemap check failed:\n' + problems.map((p) => `- ${p}`).join('\n'));
  process.exit(1);
}
console.log(`sitemap check passed: ${pages.length} canonical pages, dates consistent with repository history`);
